mysql:
  dsn: "root:ajddwWud@tcp(172.16.32.20:50320)/TinyTik?charset=utf8mb4&parseTime=True&loc=Local"
  dsn_no_db: "root:ajddwWud@tcp(172.16.32.20:50320)/?charset=utf8mb4&parseTime=True&loc=Local"
  user: root
  password: ajddwWud
  ip: "172.16.32.20"
  port: "50320"
  ipport: "172.16.32.20:50320"

redis:
  ip: "172.16.32.20"
  auth: HerJEXsH
  port: "50321"